@echo off
rem Builds c64\female_sam.prg plus the test programs used by tools\check_c64.py.
rem Needs cc65 (set CC65_HOME; default %USERPROFILE%\cc65) and Python.
rem
rem SAM's front end (src\*.c and its assembly versions) is built for target
rem "none": the c64 target would translate character constants such as 'A'
rem to PETSCII in both cc65 and ca65, and SAM's text rules are ASCII.
rem c64\reciter_index.s is generated by tools\gen_rule_index.py (rerun it if
rem src\ReciterTabs.h changes); c64\samtables.s by tools\gen_c64_tables.py.
setlocal
if "%CC65_HOME%"=="" set CC65_HOME=%USERPROFILE%\cc65
set BIN=%CC65_HOME%\bin
set OPT=-Oirs --static-locals -Isrc
set FRONTASM=render_fast render_asm reciter_asm reciter_index parser_asm parser_index sammain_asm
cd /d "%~dp0.."
if not exist c64\build mkdir c64\build
python tools\gen_c64_tables.py || exit /b 1

rem --- the C64 program
for %%f in (sam reciter render female) do (
    "%BIN%\cl65.exe" -t none %OPT% -c -o c64\build\%%f.o src\%%f.c || exit /b 1
)
for %%f in (%FRONTASM%) do (
    "%BIN%\ca65.exe" -t none -o c64\build\%%f.o c64\%%f.s || exit /b 1
)
"%BIN%\cl65.exe" -t c64 -C c64\sam_c64.cfg %OPT% -m c64\build\female_sam.map -Ln c64\build\female_sam.lbl ^
    -o c64\female_sam.prg c64\main.c c64\samout.s c64\samtables.s ^
    c64\build\render_fast.o c64\build\render_asm.o c64\build\reciter_asm.o c64\build\reciter_index.o ^
    c64\build\parser_asm.o c64\build\parser_index.o c64\build\sammain_asm.o c64\build\sam.o c64\build\reciter.o c64\build\render.o c64\build\female.o || exit /b 1
echo built c64\female_sam.prg

rem --- front-end test for sim65 (check_c64.py frames)
"%BIN%\cl65.exe" -t sim6502 %OPT% -o c64\build\test_frames.prg c64\test_frames.c ^
    src\sam.c src\reciter.c src\render.c src\female.c ^
    c64\build\render_fast.o c64\build\render_asm.o c64\build\reciter_asm.o c64\build\reciter_index.o ^
    c64\build\parser_asm.o c64\build\parser_index.o c64\build\sammain_asm.o || exit /b 1

rem --- output-loop harness for py65 (check_c64.py output): SamPlay and SamPlayTables
"%BIN%\ca65.exe" -D SAM_TEST -o c64\test\samout.o c64\samout.s || exit /b 1
"%BIN%\ca65.exe" -o c64\test\samtables.o c64\samtables.s || exit /b 1
"%BIN%\ca65.exe" -o c64\test\harness.o c64\test\harness.s || exit /b 1
"%BIN%\ld65.exe" -C c64\test\test.cfg -Ln c64\test\harness.lbl -o c64\test\harness.bin ^
    c64\test\harness.o c64\test\samout.o c64\test\samtables.o || exit /b 1
echo built test programs
endlocal
