; Generated by tools/gen_rule_index.py - do not edit.
; Positions of the reciter rules' bit-7 bytes, for reciter_asm.s.

        .export RULE_ENDS, LETTER_START_LO, LETTER_START_HI, PUNCT_START
        .import _rules, _rules2
        .segment "RODATA"

RULE_ENDS:              ; 472 entries: pointer, '(' ')' '=' offsets
        .word _rules+1
        .byte 2, 5, 6
        .word _rules+13
        .byte 1, 3, 5
        .word _rules+20
        .byte 2, 6, 8
        .word _rules+31
        .byte 2, 5, 7
        .word _rules+41
        .byte 1, 4, 6
        .word _rules+51
        .byte 3, 6, 8
        .word _rules+63
        .byte 1, 3, 6
        .word _rules+71
        .byte 1, 4, 5
        .word _rules+79
        .byte 3, 7, 8
        .word _rules+93
        .byte 1, 3, 7
        .word _rules+103
        .byte 3, 8, 9
        .word _rules+116
        .byte 2, 5, 7
        .word _rules+125
        .byte 1, 7, 8
        .word _rules+140
        .byte 3, 6, 8
        .word _rules+151
        .byte 1, 3, 6
        .word _rules+159
        .byte 1, 3, 8
        .word _rules+169
        .byte 3, 5, 9
        .word _rules+181
        .byte 2, 6, 7
        .word _rules+191
        .byte 1, 5, 6
        .word _rules+201
        .byte 3, 6, 8
        .word _rules+213
        .byte 1, 4, 5
        .word _rules+222
        .byte 1, 5, 6
        .word _rules+232
        .byte 1, 4, 5
        .word _rules+240
        .byte 1, 4, 5
        .word _rules+248
        .byte 1, 4, 5
        .word _rules+256
        .byte 3, 6, 8
        .word _rules+266
        .byte 3, 7, 9
        .word _rules+278
        .byte 1, 5, 6
        .word _rules+288
        .byte 1, 4, 6
        .word _rules+297
        .byte 3, 8, 9
        .word _rules+312
        .byte 1, 6, 7
        .word _rules+324
        .byte 1, 3, 6
        .word _rules+333
        .byte 1, 5, 7
        .word _rules+345
        .byte 1, 7, 8
        .word _rules+362
        .byte 1, 3, 7
        .word _rules+371
        .byte 1, 3, 7
        .word _rules+380
        .byte 2, 5, 7
        .word _rules+390
        .byte 2, 4, 6
        .word _rules+398
        .byte 1, 3, 4
        .word _rules+404
        .byte 4, 6, 8
        .word _rules+406
        .byte 2, 4, 6
        .word _rules+416
        .byte 2, 5, 8
        .word _rules+427
        .byte 1, 7, 8
        .word _rules+443
        .byte 2, 7, 9
        .word _rules+458
        .byte 2, 6, 8
        .word _rules+471
        .byte 1, 7, 8
        .word _rules+485
        .byte 1, 6, 7
        .word _rules+497
        .byte 1, 3, 4
        .word _rules+502
        .byte 4, 6, 8
        .word _rules+504
        .byte 2, 4, 6
        .word _rules+514
        .byte 2, 5, 7
        .word _rules+522
        .byte 3, 6, 7
        .word _rules+530
        .byte 1, 5, 8
        .word _rules+542
        .byte 1, 4, 5
        .word _rules+549
        .byte 3, 6, 8
        .word _rules+561
        .byte 1, 4, 6
        .word _rules+569
        .byte 1, 4, 6
        .word _rules+577
        .byte 1, 4, 7
        .word _rules+586
        .byte 1, 6, 7
        .word _rules+599
        .byte 1, 3, 5
        .word _rules+605
        .byte 1, 4, 5
        .word _rules+611
        .byte 1, 11, 12
        .word _rules+634
        .byte 1, 5, 6
        .word _rules+644
        .byte 1, 6, 7
        .word _rules+655
        .byte 1, 6, 7
        .word _rules+668
        .byte 1, 3, 4
        .word _rules+673
        .byte 4, 6, 8
        .word _rules+675
        .byte 2, 4, 6
        .word _rules+685
        .byte 2, 6, 8
        .word _rules+701
        .byte 3, 7, 9
        .word _rules+714
        .byte 3, 5, 7
        .word _rules+722
        .byte 5, 7, 9
        .word _rules+732
        .byte 2, 5, 8
        .word _rules+743
        .byte 2, 5, 7
        .word _rules+753
        .byte 2, 7, 8
        .word _rules+765
        .byte 1, 6, 8
        .word _rules+778
        .byte 1, 7, 8
        .word _rules+794
        .byte 2, 6, 7
        .word _rules+804
        .byte 2, 5, 7
        .word _rules+814
        .byte 2, 5, 8
        .word _rules+825
        .byte 1, 3, 4
        .word _rules+830
        .byte 4, 6, 8
        .word _rules+832
        .byte 2, 4, 6
        .word _rules+843
        .byte 3, 5, 7
        .word _rules+850
        .byte 4, 6, 8
        .word _rules+858
        .byte 3, 5, 7
        .word _rules+867
        .byte 2, 5, 7
        .word _rules+875
        .byte 3, 5, 8
        .word _rules+883
        .byte 1, 4, 7
        .word _rules+894
        .byte 1, 3, 6
        .word _rules+903
        .byte 1, 5, 7
        .word _rules+916
        .byte 1, 5, 6
        .word _rules+928
        .byte 3, 6, 8
        .word _rules+938
        .byte 1, 7, 8
        .word _rules+953
        .byte 1, 7, 8
        .word _rules+968
        .byte 1, 4, 6
        .word _rules+977
        .byte 1, 4, 5
        .word _rules+984
        .byte 2, 7, 8
        .word _rules+998
        .byte 3, 5, 7
        .word _rules+1005
        .byte 2, 5, 6
        .word _rules+1013
        .byte 1, 4, 5
        .word _rules+1021
        .byte 1, 3, 5
        .word _rules+1028
        .byte 4, 7, 9
        .word _rules+1040
        .byte 3, 5, 8
        .word _rules+1048
        .byte 3, 7, 9
        .word _rules+1060
        .byte 3, 9, 10
        .word _rules+1075
        .byte 1, 6, 7
        .word _rules+1086
        .byte 1, 4, 5
        .word _rules+1094
        .byte 1, 6, 7
        .word _rules+1105
        .byte 2, 6, 8
        .word _rules+1116
        .byte 1, 5, 6
        .word _rules+1125
        .byte 3, 6, 8
        .word _rules+1137
        .byte 1, 4, 7
        .word _rules+1147
        .byte 1, 4, 5
        .word _rules+1155
        .byte 1, 6, 7
        .word _rules+1165
        .byte 1, 4, 5
        .word _rules+1173
        .byte 2, 6, 7
        .word _rules+1183
        .byte 1, 4, 5
        .word _rules+1190
        .byte 1, 4, 5
        .word _rules+1199
        .byte 1, 7, 8
        .word _rules+1214
        .byte 1, 3, 4
        .word _rules+1220
        .byte 4, 6, 8
        .word _rules+1222
        .byte 2, 4, 6
        .word _rules+1232
        .byte 1, 5, 6
        .word _rules+1242
        .byte 1, 8, 9
        .word _rules+1258
        .byte 1, 8, 9
        .word _rules+1275
        .byte 1, 3, 5
        .word _rules+1280
        .byte 1, 3, 4
        .word _rules+1285
        .byte 4, 6, 8
        .word _rules+1287
        .byte 2, 4, 6
        .word _rules+1297
        .byte 1, 5, 6
        .word _rules+1308
        .byte 2, 4, 7
        .word _rules+1316
        .byte 1, 4, 6
        .word _rules+1326
        .byte 3, 8, 9
        .word _rules+1341
        .byte 1, 4, 5
        .word _rules+1347
        .byte 4, 6, 7
        .word _rules+1355
        .byte 1, 3, 5
        .word _rules+1361
        .byte 1, 7, 8
        .word _rules+1375
        .byte 1, 5, 7
        .word _rules+1387
        .byte 2, 5, 6
        .word _rules+1393
        .byte 2, 5, 6
        .word _rules+1400
        .byte 1, 3, 4
        .word _rules+1405
        .byte 4, 6, 8
        .word _rules+1407
        .byte 2, 4, 6
        .word _rules+1418
        .byte 2, 6, 7
        .word _rules+1431
        .byte 2, 7, 8
        .word _rules+1444
        .byte 2, 7, 8
        .word _rules+1457
        .byte 1, 5, 6
        .word _rules+1467
        .byte 1, 3, 5
        .word _rules+1474
        .byte 1, 3, 4
        .word _rules+1478
        .byte 4, 7, 8
        .word _rules+1480
        .byte 2, 5, 6
        .word _rules+1489
        .byte 2, 4, 6
        .word _rules+1498
        .byte 1, 3, 5
        .word _rules+1505
        .byte 1, 4, 6
        .word _rules+1515
        .byte 4, 6, 7
        .word _rules+1524
        .byte 5, 7, 8
        .word _rules+1534
        .byte 1, 5, 6
        .word _rules+1544
        .byte 4, 8, 10
        .word _rules+1557
        .byte 1, 5, 7
        .word _rules+1568
        .byte 1, 5, 6
        .word _rules+1579
        .byte 1, 4, 6
        .word _rules+1590
        .byte 1, 4, 5
        .word _rules+1598
        .byte 3, 5, 8
        .word _rules+1609
        .byte 3, 6, 8
        .word _rules+1620
        .byte 1, 3, 5
        .word _rules+1627
        .byte 1, 4, 5
        .word _rules+1635
        .byte 2, 7, 8
        .word _rules+1651
        .byte 1, 3, 8
        .word _rules+1661
        .byte 1, 4, 6
        .word _rules+1670
        .byte 1, 4, 6
        .word _rules+1679
        .byte 1, 4, 6
        .word _rules+1688
        .byte 3, 5, 8
        .word _rules+1698
        .byte 3, 5, 8
        .word _rules+1708
        .byte 4, 6, 9
        .word _rules+1719
        .byte 1, 3, 6
        .word _rules+1727
        .byte 1, 4, 5
        .word _rules+1734
        .byte 1, 5, 6
        .word _rules+1743
        .byte 1, 5, 6
        .word _rules+1754
        .byte 2, 6, 7
        .word _rules+1765
        .byte 1, 5, 7
        .word _rules+1776
        .byte 1, 5, 7
        .word _rules+1787
        .byte 1, 5, 7
        .word _rules+1798
        .byte 1, 6, 7
        .word _rules+1812
        .byte 1, 6, 7
        .word _rules+1823
        .byte 1, 3, 4
        .word _rules+1829
        .byte 4, 6, 8
        .word _rules+1831
        .byte 2, 4, 6
        .word _rules+1841
        .byte 1, 3, 4
        .word _rules+1846
        .byte 4, 6, 8
        .word _rules+1848
        .byte 2, 4, 6
        .word _rules+1858
        .byte 2, 4, 6
        .word _rules+1864
        .byte 1, 3, 4
        .word _rules+1869
        .byte 4, 6, 8
        .word _rules+1871
        .byte 2, 4, 6
        .word _rules+1881
        .byte 1, 4, 7
        .word _rules+1891
        .byte 2, 4, 5
        .word _rules+1896
        .byte 4, 6, 8
        .word _rules+1906
        .byte 1, 6, 7
        .word _rules+1917
        .byte 2, 8, 9
        .word _rules+1931
        .byte 1, 3, 4
        .word _rules+1936
        .byte 4, 6, 8
        .word _rules+1938
        .byte 2, 4, 6
        .word _rules+1948
        .byte 2, 6, 8
        .word _rules+1964
        .byte 2, 6, 7
        .word _rules+1976
        .byte 2, 7, 9
        .word _rules+1993
        .byte 1, 5, 6
        .word _rules+2004
        .byte 1, 8, 9
        .word _rules+2022
        .byte 2, 4, 5
        .word _rules+2027
        .byte 1, 3, 4
        .word _rules+2032
        .byte 4, 6, 8
        .word _rules+2034
        .byte 2, 4, 6
        .word _rules+2044
        .byte 2, 5, 7
        .word _rules+2053
        .byte 1, 4, 6
        .word _rules+2062
        .byte 1, 4, 6
        .word _rules+2071
        .byte 1, 5, 7
        .word _rules+2083
        .byte 1, 4, 5
        .word _rules+2090
        .byte 1, 4, 5
        .word _rules+2098
        .byte 2, 6, 8
        .word _rules+2110
        .byte 2, 4, 5
        .word _rules+2115
        .byte 1, 5, 7
        .word _rules+2127
        .byte 1, 3, 4
        .word _rules+2132
        .byte 4, 6, 8
        .word _rules+2134
        .byte 2, 4, 6
        .word _rules+2144
        .byte 1, 4, 6
        .word _rules+2153
        .byte 2, 5, 7
        .word _rules+2163
        .byte 1, 8, 9
        .word _rules+2177
        .byte 3, 6, 8
        .word _rules+2187
        .byte 3, 7, 9
        .word _rules+2199
        .byte 1, 4, 5
        .word _rules+2207
        .byte 2, 6, 7
        .word _rules+2218
        .byte 2, 6, 8
        .word _rules+2230
        .byte 1, 4, 5
        .word _rules+2237
        .byte 2, 7, 8
        .word _rules+2251
        .byte 3, 5, 7
        .word _rules+2261
        .byte 1, 4, 5
        .word _rules+2270
        .byte 1, 3, 6
        .word _rules+2279
        .byte 1, 3, 7
        .word _rules+2288
        .byte 1, 3, 7
        .word _rules+2298
        .byte 1, 4, 6
        .word _rules+2308
        .byte 1, 7, 8
        .word _rules+2320
        .byte 1, 6, 7
        .word _rules+2331
        .byte 2, 5, 6
        .word _rules+2339
        .byte 2, 5, 8
        .word _rules+2350
        .byte 1, 5, 6
        .word _rules+2359
        .byte 1, 5, 6
        .word _rules+2368
        .byte 1, 6, 7
        .word _rules+2379
        .byte 1, 4, 7
        .word _rules+2389
        .byte 1, 5, 6
        .word _rules+2399
        .byte 1, 4, 5
        .word _rules+2406
        .byte 1, 4, 5
        .word _rules+2413
        .byte 1, 6, 7
        .word _rules+2427
        .byte 1, 4, 5
        .word _rules+2435
        .byte 1, 5, 6
        .word _rules+2445
        .byte 1, 5, 6
        .word _rules+2455
        .byte 2, 6, 7
        .word _rules+2466
        .byte 2, 6, 7
        .word _rules+2477
        .byte 2, 6, 7
        .word _rules+2488
        .byte 1, 5, 6
        .word _rules+2498
        .byte 2, 6, 7
        .word _rules+2509
        .byte 1, 4, 5
        .word _rules+2517
        .byte 1, 4, 5
        .word _rules+2524
        .byte 1, 3, 5
        .word _rules+2531
        .byte 1, 3, 5
        .word _rules+2538
        .byte 1, 4, 5
        .word _rules+2546
        .byte 2, 7, 8
        .word _rules+2561
        .byte 2, 7, 8
        .word _rules+2575
        .byte 1, 6, 7
        .word _rules+2587
        .byte 2, 4, 6
        .word _rules+2595
        .byte 1, 3, 6
        .word _rules+2603
        .byte 4, 6, 8
        .word _rules+2613
        .byte 2, 5, 6
        .word _rules+2621
        .byte 3, 6, 7
        .word _rules+2630
        .byte 3, 6, 7
        .word _rules+2639
        .byte 1, 3, 6
        .word _rules+2647
        .byte 1, 4, 6
        .word _rules+2657
        .byte 1, 7, 8
        .word _rules+2672
        .byte 2, 4, 6
        .word _rules+2681
        .byte 3, 5, 8
        .word _rules+2692
        .byte 1, 5, 7
        .word _rules+2703
        .byte 4, 7, 8
        .word _rules+2714
        .byte 1, 3, 4
        .word _rules+2720
        .byte 4, 6, 8
        .word _rules+2722
        .byte 2, 4, 6
        .word _rules+2732
        .byte 1, 4, 5
        .word _rules+2738
        .byte 1, 7, 8
        .word _rules+2753
        .byte 1, 5, 6
        .word _rules+2763
        .byte 1, 5, 7
        .word _rules+2774
        .byte 1, 3, 5
        .word _rules+2779
        .byte 1, 3, 5
        .word _rules+2784
        .byte 1, 3, 5
        .word _rules+2789
        .byte 1, 7, 8
        .word _rules+2808
        .byte 1, 3, 4
        .word _rules+2813
        .byte 4, 6, 8
        .word _rules+2815
        .byte 2, 4, 6
        .word _rules+2826
        .byte 1, 6, 7
        .word _rules+2839
        .byte 1, 4, 5
        .word _rules+2846
        .byte 1, 3, 4
        .word _rules+2851
        .byte 4, 6, 8
        .word _rules+2853
        .byte 2, 4, 6
        .word _rules+2863
        .byte 2, 5, 8
        .word _rules+2874
        .byte 1, 3, 5
        .word _rules+2879
        .byte 1, 3, 4
        .word _rules+2884
        .byte 4, 6, 8
        .word _rules+2886
        .byte 2, 4, 6
        .word _rules+2896
        .byte 1, 4, 5
        .word _rules+2903
        .byte 2, 7, 8
        .word _rules+2915
        .byte 1, 6, 7
        .word _rules+2926
        .byte 2, 6, 8
        .word _rules+2938
        .byte 1, 5, 7
        .word _rules+2949
        .byte 2, 5, 7
        .word _rules+2960
        .byte 2, 6, 8
        .word _rules+2972
        .byte 2, 6, 7
        .word _rules+2981
        .byte 2, 4, 6
        .word _rules+2988
        .byte 1, 6, 7
        .word _rules+2999
        .byte 2, 7, 8
        .word _rules+3011
        .byte 1, 3, 5
        .word _rules+3016
        .byte 2, 4, 6
        .word _rules+3023
        .byte 5, 7, 9
        .word _rules+3033
        .byte 5, 7, 9
        .word _rules+3043
        .byte 2, 4, 6
        .word _rules+3050
        .byte 4, 6, 8
        .word _rules+3059
        .byte 3, 5, 7
        .word _rules+3067
        .byte 2, 6, 7
        .word _rules+3076
        .byte 1, 3, 6
        .word _rules+3082
        .byte 2, 5, 6
        .word _rules+3091
        .byte 2, 5, 7
        .word _rules+3101
        .byte 1, 6, 7
        .word _rules+3111
        .byte 1, 3, 4
        .word _rules+3116
        .byte 4, 6, 8
        .word _rules+3118
        .byte 2, 4, 6
        .word _rules+3128
        .byte 2, 6, 9
        .word _rules+3141
        .byte 2, 6, 8
        .word _rules+3153
        .byte 1, 4, 6
        .word _rules+3162
        .byte 2, 7, 8
        .word _rules+3175
        .byte 2, 7, 9
        .word _rules+3189
        .byte 2, 7, 8
        .word _rules+3201
        .byte 2, 8, 9
        .word _rules+3215
        .byte 1, 6, 7
        .word _rules+3226
        .byte 1, 7, 8
        .word _rules+3239
        .byte 2, 7, 9
        .word _rules+3253
        .byte 2, 7, 9
        .word _rules+3267
        .byte 1, 7, 9
        .word _rules+3281
        .byte 2, 7, 8
        .word _rules+3294
        .byte 1, 9, 10
        .word _rules+3310
        .byte 1, 7, 8
        .word _rules+3323
        .byte 1, 8, 10
        .word _rules+3337
        .byte 1, 7, 8
        .word _rules+3351
        .byte 1, 6, 11
        .word _rules+3368
        .byte 1, 4, 8
        .word _rules+3380
        .byte 2, 7, 8
        .word _rules+3394
        .byte 1, 4, 5
        .word _rules+3401
        .byte 3, 7, 8
        .word _rules+3413
        .byte 2, 5, 8
        .word _rules+3423
        .byte 1, 4, 6
        .word _rules+3431
        .byte 1, 4, 6
        .word _rules+3439
        .byte 1, 6, 7
        .word _rules+3450
        .byte 1, 5, 7
        .word _rules+3461
        .byte 1, 4, 6
        .word _rules+3471
        .byte 2, 6, 7
        .word _rules+3481
        .byte 2, 4, 8
        .word _rules+3489
        .byte 1, 3, 4
        .word _rules+3494
        .byte 4, 6, 8
        .word _rules+3496
        .byte 2, 4, 6
        .word _rules+3506
        .byte 2, 5, 7
        .word _rules+3517
        .byte 2, 5, 6
        .word _rules+3526
        .byte 2, 7, 8
        .word _rules+3540
        .byte 2, 5, 7
        .word _rules+3551
        .byte 1, 4, 6
        .word _rules+3562
        .byte 1, 4, 5
        .word _rules+3569
        .byte 1, 3, 6
        .word _rules+3577
        .byte 1, 3, 6
        .word _rules+3586
        .byte 1, 4, 5
        .word _rules+3594
        .byte 3, 5, 7
        .word _rules+3601
        .byte 2, 4, 6
        .word _rules+3607
        .byte 2, 4, 6
        .word _rules+3614
        .byte 3, 5, 6
        .word _rules+3623
        .byte 2, 4, 5
        .word _rules+3630
        .byte 1, 3, 4
        .word _rules+3637
        .byte 4, 6, 8
        .word _rules+3639
        .byte 2, 4, 6
        .word _rules+3649
        .byte 1, 6, 7
        .word _rules+3661
        .byte 1, 3, 4
        .word _rules+3666
        .byte 4, 6, 8
        .word _rules+3668
        .byte 2, 4, 6
        .word _rules+3684
        .byte 2, 7, 8
        .word _rules+3695
        .byte 1, 4, 7
        .word _rules+3705
        .byte 1, 4, 7
        .word _rules+3715
        .byte 1, 4, 6
        .word _rules+3724
        .byte 1, 4, 6
        .word _rules+3733
        .byte 1, 7, 8
        .word _rules+3746
        .byte 1, 6, 7
        .word _rules+3758
        .byte 1, 6, 7
        .word _rules+3770
        .byte 1, 5, 6
        .word _rules+3780
        .byte 1, 4, 5
        .word _rules+3787
        .byte 1, 5, 7
        .word _rules+3798
        .byte 1, 5, 6
        .word _rules+3808
        .byte 1, 5, 7
        .word _rules+3818
        .byte 1, 4, 5
        .word _rules+3824
        .byte 1, 5, 7
        .word _rules+3835
        .byte 1, 5, 7
        .word _rules+3846
        .byte 1, 5, 7
        .word _rules+3856
        .byte 1, 6, 7
        .word _rules+3869
        .byte 4, 8, 9
        .word _rules+3880
        .byte 1, 3, 4
        .word _rules+3885
        .byte 4, 6, 8
        .word _rules+3887
        .byte 2, 4, 6
        .word _rules+3898
        .byte 2, 4, 5
        .word _rules+3904
        .byte 1, 3, 4
        .word _rules+3910
        .byte 4, 6, 8
        .word _rules+3912
        .byte 2, 4, 6
        .word _rules+3922
        .byte 1, 7, 8
        .word _rules+3935
        .byte 2, 7, 8
        .word _rules+3947
        .byte 2, 6, 7
        .word _rules+3957
        .byte 2, 6, 7
        .word _rules+3968
        .byte 2, 4, 5
        .word _rules+3974
        .byte 2, 4, 5
        .word _rules+3981
        .byte 3, 7, 8
        .word _rules+3992
        .byte 4, 6, 7
        .word _rules+4001
        .byte 4, 6, 8
        .word _rules+4011
        .byte 3, 5, 7
        .word _rules+4020
        .byte 3, 5, 7
        .word _rules+4029
        .byte 3, 5, 10
        .word _rules+4041
        .byte 3, 5, 8
        .word _rules+4051
        .byte 1, 3, 4
        .word _rules+4057
        .byte 4, 6, 8
        .word _rules+4059
        .byte 2, 4, 6
        .word _rules+4069
        .byte 1, 3, 4
        .word _rules+4074
        .byte 0, 0, 0
        .word _rules+4075
        .byte 0, 0, 0
        .word _rules2+3
        .byte 1, 3, 4
        .word _rules2+8
        .byte 1, 3, 5
        .word _rules2+24
        .byte 1, 3, 4
        .word _rules2+35
        .byte 1, 3, 4
        .word _rules2+48
        .byte 1, 3, 4
        .word _rules2+60
        .byte 1, 3, 4
        .word _rules2+74
        .byte 1, 3, 4
        .word _rules2+83
        .byte 1, 3, 4
        .word _rules2+87
        .byte 1, 3, 4
        .word _rules2+103
        .byte 1, 3, 4
        .word _rules2+114
        .byte 1, 3, 4
        .word _rules2+119
        .byte 2, 4, 6
        .word _rules2+126
        .byte 1, 3, 4
        .word _rules2+130
        .byte 1, 3, 4
        .word _rules2+140
        .byte 1, 3, 4
        .word _rules2+152
        .byte 1, 3, 4
        .word _rules2+164
        .byte 2, 6, 7
        .word _rules2+177
        .byte 2, 7, 8
        .word _rules2+192
        .byte 1, 3, 4
        .word _rules2+202
        .byte 2, 6, 7
        .word _rules2+217
        .byte 1, 3, 4
        .word _rules2+226
        .byte 2, 6, 7
        .word _rules2+239
        .byte 1, 3, 4
        .word _rules2+250
        .byte 1, 3, 4
        .word _rules2+260
        .byte 2, 6, 7
        .word _rules2+274
        .byte 1, 3, 4
        .word _rules2+284
        .byte 2, 5, 7
        .word _rules2+305
        .byte 1, 3, 4
        .word _rules2+316
        .byte 1, 3, 4
        .word _rules2+328
        .byte 2, 6, 7
        .word _rules2+340
        .byte 1, 3, 4
        .word _rules2+349
        .byte 1, 3, 4
        .word _rules2+359
        .byte 1, 3, 4
        .word _rules2+364
        .byte 1, 3, 4
        .word _rules2+369
        .byte 1, 3, 4
        .word _rules2+385
        .byte 1, 3, 4
        .word _rules2+398
        .byte 1, 3, 4
        .word _rules2+417
        .byte 1, 3, 4
        .word _rules2+422
        .byte 1, 3, 4
        .word _rules2+431
        .byte 1, 3, 4
        .word _rules2+444
        .byte 0, 0, 0
        .word _rules2+446
        .byte 0, 0, 0

LETTER_START_LO:
        .byte <(RULE_ENDS+0), <(RULE_ENDS+200), <(RULE_ENDS+245), <(RULE_ENDS+335), <(RULE_ENDS+405), <(RULE_ENDS+610), <(RULE_ENDS+645), <(RULE_ENDS+715), <(RULE_ENDS+755), <(RULE_ENDS+935), <(RULE_ENDS+950), <(RULE_ENDS+970), <(RULE_ENDS+1010), <(RULE_ENDS+1055), <(RULE_ENDS+1115), <(RULE_ENDS+1415), <(RULE_ENDS+1470), <(RULE_ENDS+1495), <(RULE_ENDS+1520), <(RULE_ENDS+1650), <(RULE_ENDS+1815), <(RULE_ENDS+1900), <(RULE_ENDS+1920), <(RULE_ENDS+2030), <(RULE_ENDS+2050), <(RULE_ENDS+2130)
LETTER_START_HI:
        .byte >(RULE_ENDS+0), >(RULE_ENDS+200), >(RULE_ENDS+245), >(RULE_ENDS+335), >(RULE_ENDS+405), >(RULE_ENDS+610), >(RULE_ENDS+645), >(RULE_ENDS+715), >(RULE_ENDS+755), >(RULE_ENDS+935), >(RULE_ENDS+950), >(RULE_ENDS+970), >(RULE_ENDS+1010), >(RULE_ENDS+1055), >(RULE_ENDS+1115), >(RULE_ENDS+1415), >(RULE_ENDS+1470), >(RULE_ENDS+1495), >(RULE_ENDS+1520), >(RULE_ENDS+1650), >(RULE_ENDS+1815), >(RULE_ENDS+1900), >(RULE_ENDS+1920), >(RULE_ENDS+2030), >(RULE_ENDS+2050), >(RULE_ENDS+2130)
PUNCT_START = RULE_ENDS+2150
