"""Generates c64/samtables.s: the lookup tables of the 6502 output loop.

    python tools/gen_c64_tables.py

SAM's loop needs amplitude x waveform products every tick, and a 6502 has no
multiply, so they are precomputed (the original did the same):

  SINTAB  16 pages:  SINTAB[a][phase]  = round(sinus[phase] * a / 32)
  RECTAB  16 pages:  RECTAB[a][phase]  = round(rectangle[phase] * a / 32)
  NIBTAB   1 page:   NIBTAB[sum]       = ((sum + 128) & 255) >> 4

The three terms are added mod 256 and NIBTAB turns the sum into the 4-bit
value for the SID volume register, matching render.c's
  ((sin1 + sin2 + rect) / 32 + 128) >> 4
except for rounding of the individual terms.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def c_table(src, name):
    body = src[src.index(name):]
    body = body[body.index("{") + 1:body.index("};")]
    body = re.sub(r"//.*", "", body)
    return [int(v.strip(), 0) for v in body.split(",") if v.strip()]


def signed(v):
    return v - 256 if v > 127 else v


def main():
    src = open(os.path.join(ROOT, "src", "RenderTabs.h")).read()
    sinus = [signed(v & 255) for v in c_table(src, "sinus[256]")]
    rect = [signed(v) for v in c_table(src, "rectangle[]")]
    assert len(sinus) == 256 and len(rect) == 256

    def rows(wave):
        return [[round(w * a / 32) & 255 for w in wave] for a in range(16)]

    nib = [((s + 128) & 255) >> 4 for s in range(256)]

    out = ["; Generated by tools/gen_c64_tables.py - do not edit.",
           "; Amplitude x waveform products for the SAM output loop (see that script).",
           "", '        .export SINTAB, RECTAB, NIBTAB', '        .segment "SAMTAB"', ""]

    def emit(label, pages):
        out.append(f"{label}:")
        for page in pages:
            for i in range(0, 256, 16):
                out.append("        .byte " + ",".join(f"${v:02X}" for v in page[i:i + 16]))
        out.append("")

    emit("SINTAB", rows(sinus))
    emit("RECTAB", rows(rect))
    emit("NIBTAB", [nib])
    path = os.path.join(ROOT, "c64", "samtables.s")
    open(path, "w").write("\n".join(out))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
