"""Vowel tables for engine A (src/rules_tables.h) from Hillenbrand et al. (1995).

    python tools/gen_rules_tables.py [path/to/vowdata.dat]

For the 45 men and 48 women: mean F1-F3 at 20% and 50% of each vowel (its
onset and offset targets, which keep the natural glide of /e/, /o/ and the
lax vowels), the vowel's relative duration and its intrinsic F0 relative to
the talker group's mean. ARPAbet vowels Hillenbrand did not record are built
from recorded ones: AY = /a/ -> /I/, AW = /a/ -> /U/, OY = /O/ -> /I/, and the
reduced vowels AX (schwa), IX and AXR. vowdata.dat: (c) 1995 James
Hillenbrand, https://homepages.wmich.edu/~hillenbr/voweldata.html
"""
import os, sys
import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "data", "vowdata.dat")
OUT = os.path.join(ROOT, "src", "rules_tables.h")

# ARPAbet -> Hillenbrand vowel code
HV = {"IY": "iy", "IH": "ih", "EY": "ei", "EH": "eh", "AE": "ae", "AA": "ah", "AO": "aw",
      "OW": "oa", "UH": "oo", "UW": "uw", "AH": "uh", "ER": "er"}
ORDER = ["AA", "AE", "AH", "AO", "AW", "AY", "EH", "ER", "EY", "IH", "IY", "OW", "OY", "UH", "UW",
         "AX", "IX", "AXR"]


def load():
    rows = {}
    for line in open(SRC):
        p = line.split()
        if len(p) != 16 or len(p[0]) != 5 or p[0][0] not in "mw":
            continue
        sex, vowel = p[0][0], p[0][3:5]
        vals = list(map(float, p[1:]))
        rows.setdefault((sex, vowel), []).append(vals)
    return rows


def mean(rows, col):
    v = np.array([r[col] for r in rows])
    v = v[v > 0]
    return float(v.mean())


def main():
    rows = load()
    table = {}
    for sex in "mw":
        f0_all = np.mean([mean(rows[(sex, v)], 1) for v in HV.values()])
        dur_all = np.mean([mean(rows[(sex, v)], 0) for v in HV.values()])
        t = {}
        for arpa, hv in HV.items():
            r = rows[(sex, hv)]
            on = [mean(r, c) for c in (6, 7, 8)]       # F1-F3 at 20% (after /h/: no coarticulation)
            off = [mean(r, c) for c in (9, 10, 11)]    # F1-F3 at 50%; the 80% point is
            # already pulled toward the /d/ of "h_d", so the diphthongs /eI/ and /oU/
            # are extrapolated from the 20-50% movement instead
            if arpa in ("EY", "OW"):
                off = [b + 0.6 * (b - a) for a, b in zip(on, off)]
            t[arpa] = (on, off, mean(r, 0) / dur_all, mean(r, 1) / f0_all)
        mid = lambda v: [(a + b) / 2 for a, b in zip(t[v][0], t[v][1])]
        t["AY"] = (t["AA"][0], mid("IH"), 1.25, 1.0)
        t["AW"] = (t["AA"][0], mid("UH"), 1.25, 1.0)
        t["OY"] = (t["AO"][0], mid("IH"), 1.3, 1.0)
        # reduced vowels: schwa at the centre of the vowel space (average of
        # the steady states of the 12 vowels), IX between IH and schwa, AXR as ER
        centre = np.mean([mid(v) for v in HV], axis=0).tolist()
        t["AX"] = (centre, centre, 0.6, 1.0)
        ix = [(a + b) / 2 for a, b in zip(mid("IH"), centre)]
        t["IX"] = (ix, ix, 0.55, 1.0)
        t["AXR"] = (t["ER"][0], t["ER"][1], 0.65, 1.0)
        table[sex] = t
    with open(OUT, "w", newline="\n") as f:
        f.write("// Generated by tools/gen_rules_tables.py from Hillenbrand et al. (1995),\n"
                "// vowdata.dat (c) 1995 James Hillenbrand. Do not edit.\n"
                "// Per vowel: F1-F3 onset (20%) and offset (50%, extrapolated for EY, OW) in Hz, relative duration,\n"
                "// intrinsic F0 relative to the talkers' mean. [0] = men, [1] = women.\n\n")
        f.write("enum { " + ", ".join("RV_" + v for v in ORDER) + ", RV_COUNT };\n\n")
        f.write("typedef struct { short on[3], off[3]; unsigned char dur, f0; } RulesVowel;  "
                "// dur, f0: x/100\n\n")
        f.write("static const RulesVowel rulesVowels[2][RV_COUNT] =\n{\n")
        for sex in "mw":
            f.write("    {   // " + ("men" if sex == "m" else "women") + "\n")
            for v in ORDER:
                on, off, dur, f0 = table[sex][v]
                f.write("        {{%d, %d, %d}, {%d, %d, %d}, %d, %d},   // %s\n" % (
                    *[round(x) for x in on], *[round(x) for x in off], round(dur * 100), round(f0 * 100), v))
            f.write("    },\n")
        f.write("};\n")
    for v in ORDER:
        print(f"{v:4s} women on {[round(x) for x in table['w'][v][0]]} off {[round(x) for x in table['w'][v][1]]} "
              f"dur {table['w'][v][2]:.2f} f0 {table['w'][v][3]:.3f}")
    print("wrote", OUT)


main()
