"""Generates c64/reciter_index.s: where every reciter rule ends.

    python tools/gen_rule_index.py      (needs c64/build/dump_rules.exe, built by c64/build.bat)

SAM's reciter moves to the next rule by scanning forward byte by byte from the
current rule address (mem62 + 1) to the next byte with bit 7 set; the rules
live at SAM's virtual addresses 32000.. (rules[]) and 37541.. (rules2[]).
This writes those bit-7 positions in address order, so the 6502 version can
step to the next rule in a few cycles with exactly the same result:

  RULE_ENDS     per bit-7 byte, in virtual-address order: .word pointer, then
                the offsets where the C's scans for '(', ')' and '=' stop in
                the rule that follows (0: scan at run time)
  LETTER_START  per letter A..Z: address of the first RULE_ENDS entry after
                the letter's start address (tab37489/tab37515)
  PUNCT_START   the same for the punctuation rules (start address 37541)
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULES2 = 37541


def main():
    out = subprocess.run([os.path.join(ROOT, "c64", "build", "dump_rules.exe")],
                         capture_output=True, text=True, check=True).stdout
    tabs = {}
    for line in out.splitlines():
        name, n, *vals = line.split()
        tabs[name] = [int(v) for v in vals]
        assert len(tabs[name]) == int(n)
    rules, rules2 = tabs["rules"], tabs["rules2"]
    assert 32000 + len(rules) <= RULES2

    ends = [(32000 + i, f"_rules+{i}") for i, b in enumerate(rules) if b & 128]
    ends += [(RULES2 + j, f"_rules2+{j}") for j, b in enumerate(rules2) if b & 128]
    addrs = [a for a, _ in ends]

    def first_after(addr):
        return next(k for k, a in enumerate(addrs) if a > addr)

    letters = [first_after(lo | hi << 8) for lo, hi in zip(tabs["tab37489"], tabs["tab37515"])]
    punct = first_after(RULES2)

    # where the C's scans stop for the rule after each end: '(' (from Y = 1),
    # then ')', then '=' (bit 7 ignored); 0 = scan at run time (off the end)
    def offsets(arr, pos):
        try:
            y = 1
            while arr[pos + y] != ord("("):
                y += 1
            op = y
            y += 1
            while arr[pos + y] != ord(")"):
                y += 1
            cl = y
            y += 1
            while arr[pos + y] & 127 != ord("="):
                y += 1
            return (op, cl, y) if y < 256 else (0, 0, 0)
        except IndexError:
            return (0, 0, 0)
    offs = [offsets(rules, a - 32000) if a < RULES2 else offsets(rules2, a - RULES2) for a, _ in ends]

    lines = ["; Generated by tools/gen_rule_index.py - do not edit.",
             "; Positions of the reciter rules' bit-7 bytes, for reciter_asm.s.",
             "", "        .export RULE_ENDS, LETTER_START_LO, LETTER_START_HI, PUNCT_START",
             "        .import _rules, _rules2", '        .segment "RODATA"', "",
             f"RULE_ENDS:              ; {len(ends)} entries: pointer, '(' ')' '=' offsets"]
    for (_, sym), (op, cl, eq) in zip(ends, offs):
        lines.append(f"        .word {sym}")
        lines.append(f"        .byte {op}, {cl}, {eq}")
    lines.append("")
    lines.append("LETTER_START_LO:")
    lines.append("        .byte " + ", ".join(f"<(RULE_ENDS+{5 * k})" for k in letters))
    lines.append("LETTER_START_HI:")
    lines.append("        .byte " + ", ".join(f">(RULE_ENDS+{5 * k})" for k in letters))
    lines.append(f"PUNCT_START = RULE_ENDS+{5 * punct}")
    path = os.path.join(ROOT, "c64", "reciter_index.s")
    open(path, "w").write("\n".join(lines) + "\n")
    print(f"wrote {path}: {len(ends)} rule ends, {sum(1 for o in offs if o[0] == 0)} without precomputed offsets")


if __name__ == "__main__":
    main()
