"""Generates c64/parser_index.s: lookup tables for Parser1 (parser_asm.s).

    python tools/gen_parser_index.py    (needs c64/build/dump_parser.exe)

Parser1 matches each phoneme name by scanning signInputTable1/2 (81 entries)
up to twice. These tables give the same first match directly, per character:

  TWO_START[c]   offset into TWO_SECOND / TWO_PHONEME of the two-letter
                 names starting with c (second letter not '*'), in table
                 order; each list ends with a 0 in TWO_SECOND
  ONE[c]         first one-letter name c ('*' second), else 255
  STRESS[c]      the stress digit 1..8 for c (highest match, as the C's
                 downward search finds it), else 0
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    out = subprocess.run([os.path.join(ROOT, "c64", "build", "dump_parser.exe")],
                         capture_output=True, text=True, check=True).stdout
    t = {}
    for line in out.splitlines():
        name, n, *vals = line.split()
        t[name] = [int(v) for v in vals]
    t1, t2, st = t["signInputTable1"], t["signInputTable2"], t["stressInputTable"]
    star = ord("*")
    assert 0 not in [b for b in t2 if b != star]          # 0 is free as the list end

    second, phoneme, start = [], [], []
    for c in range(256):
        start.append(len(second))
        for y in range(81):
            if t1[y] == c and t2[y] != star:
                second.append(t2[y])
                phoneme.append(y)
        second.append(0)
        phoneme.append(0)
    assert len(second) <= 256 * 2
    one = [next((y for y in range(81) if t2[y] == star and t1[y] == c), 255) for c in range(256)]
    stress = [next((y for y in range(8, 0, -1) if st[y] == c), 0) for c in range(256)]

    # characters without two-letter names all share one empty list
    empty = None
    sec2, ph2, start2 = [], [], []
    for c in range(256):
        lst = []
        k = start[c]
        while second[k]:
            lst.append((second[k], phoneme[k]))
            k += 1
        if not lst:
            if empty is None:
                empty = len(sec2)
                sec2.append(0)
                ph2.append(0)
            start2.append(empty)
        else:
            start2.append(len(sec2))
            for s, p in lst:
                sec2.append(s)
                ph2.append(p)
            sec2.append(0)
            ph2.append(0)
    assert len(sec2) <= 256

    def rows(label, data):
        lines = [f"{label}:"]
        for i in range(0, len(data), 16):
            lines.append("        .byte " + ",".join(str(v) for v in data[i:i + 16]))
        return lines

    lines = ["; Generated by tools/gen_parser_index.py - do not edit.",
             "; Phoneme-name lookup tables for Parser1 (parser_asm.s).", "",
             "        .export TWO_START, TWO_SECOND, TWO_PHONEME, ONE, STRESS",
             '        .segment "RODATA"', ""]
    lines += rows("TWO_START", start2) + rows("TWO_SECOND", sec2) + rows("TWO_PHONEME", ph2)
    lines += rows("ONE", one) + rows("STRESS", stress)
    path = os.path.join(ROOT, "c64", "parser_index.s")
    open(path, "w").write("\n".join(lines) + "\n")
    print(f"wrote {path}: {len(sec2)} two-letter list bytes")


if __name__ == "__main__":
    main()
